---

- name: Install epel-release-latest-7
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install package dependencies for graphite and carbon
  yum:
    pkg: "{{item}}"
    state: present
  with_items:
     - gcc
     - python-devel
     - python-pip
     - cairo-devel
     - libffi-devel
     - httpd
     - mod_wsgi
     - openssl-devel

- name: Install other pip dependencies
  pip: name={{item}} state=present
  with_items:
    - scandir
    - Twisted==16.0.0

- name: Upgrade pyopenssl
  pip: name={{item}} state=present extra_args="--upgrade"
  with_items:
    - pyopenssl

- name: Install Graphite Components (Whisper, Carbon, Graphite-Web)
  pip: name={{item}} extra_args="--no-binary=:all:" state=present
  environment:
    PYTHONPATH: "/opt/graphite/lib/:/opt/graphite/webapp/"
  with_items:
    - https://github.com/graphite-project/whisper/archive/1.0.0.tar.gz
    - https://github.com/graphite-project/carbon/archive/1.0.0.tar.gz
    - https://github.com/graphite-project/graphite-web/archive/1.0.0.tar.gz

- name: Configure Carbon
  command: cp /opt/graphite/conf/carbon.conf.example /opt/graphite/conf/carbon.conf

- name: Configure storage-schemas.conf
  command: cp /opt/graphite/conf/storage-schemas.conf.example /opt/graphite/conf/storage-schemas.conf

- name: Configure storage-aggregation.conf
  command: cp /opt/graphite/conf/storage-aggregation.conf.example /opt/graphite/conf/storage-aggregation.conf

- name: copy graphite.wsgi
  command: cp /opt/graphite/conf/graphite.wsgi.example /opt/graphite/conf/graphite.wsgi

- name: copy graphTemplates.conf
  command: cp /opt/graphite/conf/graphTemplates.conf.example /opt/graphite/conf/graphTemplates.conf

- name: Set permissions graphite directory
  file:
    path: /opt/graphite/storage/
    owner: apache
    group: apache
    recurse: yes

- name: sync database
  shell: django-admin.py migrate --settings=graphite.settings --run-syncdb
  environment:
    PYTHONPATH: /opt/graphite/webapp

- name: replace httpd.conf by the template modified
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf force=yes
