---

- name: Create config file for Jolokia collector
  template:
    src: JolokiaCollector.conf.j2
    dest: "{{collectors_conf_path}}/JolokiaCollector.conf"
    force: yes

- name: "Create grafana dashboard for JVM in {{ dashboard_dir }}/{{ TARGET_INSTANCE }}.dashboard"
  template:
    src: dashboard.json.j2
    dest: "{{ dashboard_dir }}/{{ TARGET_INSTANCE }}-JVM.dashboard"
    force: yes
