- name: Ensure httplib2 is present
  pip:
    name: httplib2
    state: present

- set_fact:
    plugin_rest_url: "{{ cfy_url }}/api/v3/plugins?plugin_archive_url={{ plugin_archive_url|urlencode() }}"

- name: Upload plugin into CFY manager using url {{ plugin_rest_url }}
  uri:
    url: "{{ plugin_rest_url }}"
    method: POST
    validate_certs: no
    force_basic_auth: yes
    user: "{{ cfy_user }}"
    password: "{{ cfy_password }}"
    return_content: yes
    HEADER_Tenant: "default_tenant"
    status_code: 201
  ignore_errors: yes
  register: result

- debug:
    var: result
