
# Just to be compatible with both node & relationship operations
- set_fact:
    INSTANCE: "{{ SOURCE_INSTANCE }}"
  when: SOURCE_INSTANCE is defined
- set_fact:
    NODE: "{{ SOURCE_NODE }}"
  when: SOURCE_NODE is defined

- set_fact:
    file_path: "/tmp/a4cPlaybookRegistry/{{ NODE }}/{{ INSTANCE }}/attributes/{{ attribute_name }}"
- set_fact:
    file_dir: "{{ file_path | dirname }}"

# FIXME: remove
# ugly workarround to have attribute from host
- name: "Ensure directory {{ file_dir }} exists in order to publish attribute"
  file:
    path: "{{ file_dir }}"
    state: directory
  when: attribute_value is defined

- name: "Copy attribute <{{ attribute_name }}> value <{{ attribute_value }}> into {{ file_path }}"
  shell: "echo '{{ attribute_value }}' > {{ file_path }}"
  # copy:
  #   content: "{{ attribute_value }}"
  #   dest: "{{ file_path }}"
  #   remote_src: True
  when: attribute_value is defined
