
# Just to be compatible with both node & relationship operations
- set_fact:
    INSTANCE: "{{ SOURCE_INSTANCE }}"
  when: SOURCE_INSTANCE is defined

- set_fact:
    my_ips: []
    my_instance_idx: []

- name: Provision EC2 instances
  ec2:
     aws_access_key: "{{ aws_access_key }}"
     aws_secret_key: "{{ aws_secret_key }}"
     key_name: "{{ key_name }}"
     region: "{{ region }}"
     group_id: "{{ instance_groups }}"
     instance_type: "{{ instance_type }}"
     image: "{{ instance_image }}"
     wait: true
     exact_count: "{{ instance_count }}"
     count_tag:
        Name: "{{ instance_name }}"
     instance_tags:
        Name: "{{ instance_name }}"
        HostpoolFeeder: "{{ INSTANCE }}"
  register: ec2

- set_fact:
    my_ips: "{{ my_ips }} + [ '{{ item.private_ip }}' ]"
  with_items: ec2.instances

- set_fact:
    my_instance_idx: "{{ my_instance_idx }} + [ '{{ item }}' ]"
  with_sequence: "start=1 end={{ host_per_instance }}"

- name: "Add instances to hostpool using url {{ hostpool_url }}/hosts"
  uri:
    url: "{{ hostpool_url }}/hosts"
    method: POST
    return_content: yes
    body:
      hosts:
        - endpoint:
            ip: "{{ item[0] }}"
            protocol: "ssh"
            port: 22
          name: "{{ item[0] }}"
          credentials:
            username: "{{ instance_username }}"
            key: "{{ key_content }}"
          os: "{{ instance_os }}"
    body_format: json
    status_code: 201
  with_nested:
    - my_ips
    - my_instance_idx
