---
- name: Create config file for ElasticSearch collector
  template:
    src: ElasticSearchCollector.conf.j2
    dest: "{{collectors_conf_path}}/ElasticSearchCollector.conf"
    force: yes

- name: "Create grafana dashboard for ES in {{ dashboard_dir }}/{{ TARGET_INSTANCE }}-ES.dashboard"
  template:
    src: dashboard.json.j2
    dest: "{{ dashboard_dir }}/{{ TARGET_INSTANCE }}-ES.dashboard"
    force: yes
