tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.grafana.pub
  template_version: 1.4.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - tosca-normative-types:1.0.0-ALIEN14
  - org.alien4cloud.monitoring.pub:1.4.0-SNAPSHOT

node_types:

  org.alien4cloud.monitoring.pub.nodes.GrafanaService:
    derived_from: tosca.nodes.SoftwareComponent
    abstract: true
    metadata:
      icon: /images/grafana.png
    capabilities:
      http_endpoint:
        type: org.alien4cloud.grafana.pub.capabilities.GrafanaHttpEndpoint
        occurrences: [0, UNBOUNDED]
        description: UI endpoint

capability_types:
  org.alien4cloud.grafana.pub.capabilities.GrafanaHttpEndpoint:
    derived_from: tosca.capabilities.Endpoint
    properties:
      user:
        type: string
        default: admin
        required: true
      password:
        type: string
        default: admin
        required: true
