---
- hosts: all
  # connection: local
  name: Remove EC2 instance & clear Hostpool hosts
  become: true

  pre_tasks:
    - name: Debug vars
      debug:
        msg: "{{ vars | to_json }}"

  roles:
    - setup
    - { role: get_att, attribute_name: 'hostpool_url' }
    - delete
