---
- name: Create config file for Jolokia collector
  template:
    src: CloudifyCollector.conf.j2
    dest: "{{collectors_conf_path}}/CloudifyCollector.conf"
    force: yes

- name: "Create grafana dashboard for Cloudify in {{ dashboard_dir }}/{{ TARGET_INSTANCE }}.dashboard"
  template:
    src: dashboard.json.j2
    dest: "{{ dashboard_dir }}/{{ TARGET_INSTANCE }}-Cloudify.dashboard"
    force: yes
